version: '3.8'

services:
  laravelapp:
    container_name: laravelshopping
    image: laravelapp:1.0.1
    build: . 
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.31
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MAX_ALLOWED_PACKET
    volumes:
      - ../db-data-laravelshopping:/var/lib/mysql